### PR TITLE
Download gmock/gtest from github

### PR DESCRIPTION
**Pull request by konserw**
Download gmock/gtest from github as link used currently expired

### CODE REVIEW

**Comment by konserw** [comment]
Can you see why would most features fail because of tempering with gtest/gmock ?

**Comment by konserw** [comment]
ok I think I've got it - for some reason if GMOCK_ROOT is not a subdirectory it messes e2e tests

**Comment by konserw** [comment]
I've added support for gmock 1.8.0 to FindGmock but we have issue #121

**Comment by srbaker** [comment]
+1 on this. Would love to see this merged soon, as master won't even build currently. :(

**Comment by paoloambrosio** [comment]
Nice one. Haven't gone through all lines changed, but I trust the CI pipeline.

I'd squash the first 4 commits into "change gmock/gtest source to github" and keep "support for gtest/gmock >= 1.8.0".

A couple of questions:
 - What about compiling with 1.8.0 in Travis / AppVeyor?
 - Why is 1.7.0 still the default?

**Comment by paoloambrosio** [comment]
@srbaker it does compile if you specify `GMOCK_PATH` (see https://travis-ci.org/cucumber/cucumber-cpp/jobs/158838935). The CI pipeline doesn't currently run on master because it also tries to compile with the sources downloaded from GitHub.

**Comment by konserw** [comment]
I had some problems with gmock 1.8, see issue #121 - i'll need to verify what happened there :)

**Comment by paoloambrosio** [comment]
If it doesn't automaticaly work with 1.8.0 we should split the two PRs and remove last commit from this one. In the one for 1.8.0 please add that to the CI build. After that and squashing I think it can be merged to close #122 (and finally merge #116).

**Comment by konserw** [comment]
@paoloambrosio - I've fixed building with gmock 1.8 and squashed into 2 commits. 
 I've also added third commit that adds gmock 1.8.0 to travis CI

**Comment by konserw** [comment]
all green :)

**Comment by paoloambrosio** [comment]
Nice one! Green build again :+1:

**Pull request merged**
