### PR TITLE
Upgrade to the latest Ruby version and libraries

### PR DESCRIPTION
**Pull request by konserw**
Upgrade to the latest Ruby version and libraries #88 
This is as far as I could get it. 
Unfortunately I have no experience with ruby or those gems. I'm not even sure if those tests I changed are still properly testing cucumber functionalities.
Maybe I'll try working on own fork of cucumber-tck as with following gems tck itself generates deprected warnings:
-  gem 'cucumber', "=2.0.0"
-  gem 'aruba', "=0.8.0"
-  gem 'rspec', "=3.4.0"

### CODE REVIEW

**Comment by konserw** [comment]
I've forked cucumber-tck and fixed warning about #current_dir but that is not sufficient to push aruba further... See own_tck branch for that.

**Comment by paoloambrosio** [comment]
Let's live with `cucumber-tck` till we have something better (still TBD). I've created a `cucumber-cpp` branch in `cucumber-tck` if it helps getting to a stable CI pipeline.

**Comment by konserw** [comment]
as stated also in #97 - I've created PR there: https://github.com/cucumber/cucumber-tck/pull/19

**Comment by konserw** [comment]
i'll change ref here after tck PR is merged

**Comment by paoloambrosio** [comment]
Merged #105 (with 16 less commits)

**Pull request closed without merging**
