### PR TITLE
Fixed documentation

### PR DESCRIPTION
**Pull request by maxmeyer**
As discussed the upgrade and the outcome of our discussion at #cukenhagen.

### CODE REVIEW

**Comment by konserw** [comment]
A little misleading title as it has nothing to do with aruba ;)

**Comment by paoloambrosio** [comment]
@konserw: correct, the two commits have nothing to do with the title and might be moved to a separate PR

@maxmeyer is the maintainer of Aruba and has offered to help upgrading from 0.8 to 0.14!

Late in the evening, after a day of hacking, we were too tired to write the first step of something that could be committed, but at least now I know one of the problems and I'm working on it ;-)

**Comment by konserw** [comment]
Ok - good to hear that ;)

**Comment by maxmeyer** [comment]
@konserw Fixed the title. We rolled back some changes. So nothing of the upgrade was left.

**Pull request merged**
