### PR TITLE
Fix issue #127 Assignment operator not generated

### PR DESCRIPTION
**Pull request by mpjmpj**
Added a private declaration of the assignment operator to StepInfo.

### CODE REVIEW

**Comment by mpjmpj** [comment]
Let me know if I did something wrong with the pull request.  This is my first time contributing to something on github, so I'm still learning the ropes.  Thanks!

**Comment by paoloambrosio** [comment]
Thanks for this pull request. Don't worry about doing it wrong :-) The main rule is to follow the same code style as the rest of the code and write tests (TDD if possible). If you need to ask anything we have also a Gitter channel.

I cannot see the same warning on VS2015 (not 2013) run by AppVeyor.

My only concern with your implementation is that the purpose of that method is not clear, but perhaps it's just me not being a decent C++ developer. What about private inheritance from `boost::noncopyable` (that AFAIK for C++03 has your same implementation)?

**Comment by mpjmpj** [comment]
I haven't worked in many c++ shops, but my feeling that this is a common practice.  If copy constructors and assignment operators aren't defined, the compiler generates them.  If you create a class where those generated functions are invalid (if you have a const member variable or a member variable that is a reference), you define them as private to signal to the compiler to skip the generation.  In one of the latest revisions of c++ they included a new syntax `thing& operator=(const thing&) = delete`.  But I figured you probably didn't want to break compatibility with older compilers if you didn't have to.

I haven't looked into boost::noncopyable (I will try to) but my own bias would be to avoid adding dependencies when there is a simple way to accomplish the same thing.  I suppose the benefit is that it self documenting - but again, it feels like a common pattern to me as-is.  All that said, I'm playing in your sandbox, so I'm happy to do whatever.

I do feel that there is something missing from the testing.  I don't get this warning when building the cucumber-cpp project on its own (even in vs2013).  I only get it when incorporating it into my project's tests.  I feel that if those classes were invoked by the cucumber-cpp unit tests, they'd generate the warning.  I just haven't had time to really look into it as we have a bit of a deadline at work.  I still plan on trying to however - it might just be next week.

**Comment by paoloambrosio** [comment]
We already have a dependency on Boost for `boost::noncopyable`, but I'm OK merging this anyway. I'll do it ASAP.

**Pull request merged**
